UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID = '423590', INSUR_MODALITY_DESC = 'PLAN 1', INSURANCE_MODALITY_NAME = 'PLAN 1', OPERATION_GLOSSARY_DESC = 'DESEMPLEO_TC' WHERE INSURANCE_PRODUCT_ID = 11 AND INSURANCE_MODALITY_TYPE = '01';
UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID = '423591', INSUR_MODALITY_DESC = 'PLAN 2', INSURANCE_MODALITY_NAME = 'PLAN 2', OPERATION_GLOSSARY_DESC = 'DESEMPLEO_TC' WHERE INSURANCE_PRODUCT_ID = 11 AND INSURANCE_MODALITY_TYPE = '02';
UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID = '423592', INSUR_MODALITY_DESC = 'PLAN 3', INSURANCE_MODALITY_NAME = 'PLAN 3', OPERATION_GLOSSARY_DESC = 'DESEMPLEO_TC' WHERE INSURANCE_PRODUCT_ID = 11 AND INSURANCE_MODALITY_TYPE = '03';

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID = '423586', INSUR_MODALITY_DESC = 'PLAN VEHICULAR', INSURANCE_MODALITY_NAME = 'PLAN VEHICULAR', OPERATION_GLOSSARY_DESC = 'DESEMPLEO_PRESTAMO' WHERE INSURANCE_PRODUCT_ID = 11 AND INSURANCE_MODALITY_TYPE = '08';
UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID = '423290', INSUR_MODALITY_DESC = 'PLAN PLD', INSURANCE_MODALITY_NAME = 'PLAN PLD', OPERATION_GLOSSARY_DESC = 'DESEMPLEO_PRESTAMO' WHERE INSURANCE_PRODUCT_ID = 11 AND INSURANCE_MODALITY_TYPE = '09';


