update PISD.T_PISD_INSURANCE_CONTRACT IC  set PAYMENT_MEANS_TYPE = 'OP' where  IC.INSURANCE_CONTRACT_ENTITY_ID=3011 and IC.INSURANCE_CONTRACT_BRANCH_ID=0240 and IC.CONTRACT_FIRST_VERFN_DIGIT_ID=7 and 
IC.CONTRACT_SECOND_VERFN_DIGIT_ID=7 
and IC.INSRC_CONTRACT_INT_ACCOUNT_ID=4580000900;
COMMIT ;


update PISD.T_PISD_INSURANCE_CTR_RECEIPTS IC  set RECEIPT_STATUS_TYPE = 'PEN' where  IC.INSURANCE_CONTRACT_ENTITY_ID=3011 and IC.INSURANCE_CONTRACT_BRANCH_ID=0240 
and IC.INSRC_CONTRACT_INT_ACCOUNT_ID=4580000900;
COMMIT ;

