update PISD.T_PISD_INSURANCE_CONTRACT
  set INSURANCE_COMPANY_PRODUCT_ID = 1708
  WHERE CONTRACT_STATUS_ID IN ('FOR') 
  AND INSURANCE_COMPANY_PRODUCT_ID is null
  and INSURANCE_PRODUCT_ID = 11;
  
update PISD.T_PISD_INSURANCE_CONTRACT
  set INSURANCE_COMPANY_PRODUCT_ID = 8308
  WHERE CONTRACT_STATUS_ID IN ('FOR') 
  AND INSURANCE_COMPANY_PRODUCT_ID is null
  and INSURANCE_PRODUCT_ID = 8;