UPDATE PISD.T_PISD_INSURANCE_PRODUCT
SET INSURANCE_PRODUCT_DESC = 'SEGURO RESPALDO TOTAL',
INSURANCE_PRODUCT_NAME = 'SEG. RESPALDO TOTAL'
WHERE INSURANCE_PRODUCT_ID = 9;

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSUR_MODALITY_DESC = 'PLAN SIN DEVOLUCION',
INSURANCE_MODALITY_NAME = 'SEGURO DE RESPALDO TOTAL SIN DEVOLUCIÓN'
WHERE INSURANCE_PRODUCT_ID = 9
AND INSURANCE_MODALITY_TYPE = '01';

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSUR_MODALITY_DESC = 'PLAN CON DEVOLUCION',
INSURANCE_MODALITY_NAME = 'SEGURO DE RESPALDO TOTAL CON DEVOLUCIÓN'
WHERE INSURANCE_PRODUCT_ID = 9
AND INSURANCE_MODALITY_TYPE = '02';
