INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('841007','PR008002','BBVA00123492|El apellido paterno de la persona responsable es requerido, ingresar por favor','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;

INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('841007','PC008002','BBVA00123493|El apellido paterno de la persona contratante es requerido, ingresar por favor','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;

INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('841007','PR004006','BBVA00123494|El tipo de documento de la persona responsable tiene valor no valido, ingresar valores: L, P, E, R','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;