INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','00000000','Errores de datos para el canal PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;

INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR005005','BBVAE1000001|El n'||chr(250)||'mero de Documento del Responsable de pago debe tener 8 caracteres. Verificar espacios en blanco y caracteres adicionales no num'||chr(233)||'ricos','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC005005','BBVAE1000002|El n'||chr(250)||'mero de Documento del Contratante  debe tener 8 caracteres. Verificar espacios en blanco y caracteres adicionales no num'||chr(233)||'ricos','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA005005','BBVAE1000003|El n'||chr(250)||'mero de Documento del Asegurado de pago debe tener 8 caracteres. Verificar espacios en blanco y caracteres adicionales no num'||chr(233)||'ricos','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR005011','BBVAE1000004|El n'||chr(250)||'mero de Documento del Responsable de pago debe contener '||chr(250)||'nicamente n'||chr(250)||'meros. Verificar la informaci'||chr(243)||'n y corregir en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC005011','BBVAE1000005|El n'||chr(250)||'mero de Documento del Contratante debe contener '||chr(250)||'nicamente n'||chr(250)||'meros. Verificar la informaci'||chr(243)||'n y corregir en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA005011','BBVAE1000006|El n'||chr(250)||'mero de Documento del Asegurado debe contener '||chr(250)||'nicamente n'||chr(250)||'meros. Verificar la informaci'||chr(243)||'n y corregir en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR005003','BBVAE1000007|El N'||chr(250)||'mero de Documento del Responsable de Pago debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC005003','BBVAE1000008|El N'||chr(250)||'mero de Documento del Contratante  debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA005003','BBVAE1000009|El N'||chr(250)||'mero de Documento del Asegurado debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR008001','BBVAE1000010|El apellido Paterno del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC008001','BBVAE1000011|El apellido Paterno del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA008001','BBVAE1000012|El apellido Paterno del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR008002','BBVAE1000013|El apellido Paterno del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC008002','BBVAE1000014|El apellido Paterno del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA008002','BBVAE1000015|El apellido Paterno del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR008011','BBVAE1000016|El apellido paterno del responsable de pago tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC008011','BBVAE1000017|El apellido paterno del Contratante tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA008011','BBVAE1000018|El apellido paterno del Asegurado tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR008004','BBVAE1000019|El apellido paternos del Responsable de Pago supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC008004','BBVAE1000020|El apellido paternos Contratante supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA008004','BBVAE1000021|El apellido paternos del Asegurado supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR009011','BBVAE1000022|El apellido Materno del responsable de pago tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC009011','BBVAE1000023|El apellido Materno del Contratante tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA009011','BBVAE1000024|El apellido paterno del Asegurado tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR009004','BBVAE1000025|El apellido Materno del Responsable de Pago supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC009004','BBVAE1000026|El apellido Materno Contratante supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA009004','BBVAE1000027|El apellido Materno del Asegurado supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR009002','BBVAE1000028|El apellido Materno del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC009002','BBVAE1000029|El apellido Materno del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA009002','BBVAE1000030|El apellido Materno del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR010001','BBVAE1000031|Los nombres del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC010001','BBVAE1000032|Los nombres del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA010001','BBVAE1000033|Los nombres del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR010002','BBVAE1000034|Los nombres del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC010002','BBVAE1000035|Los nombres del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA010002','BBVAE1000036|Los nombres del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR010011','BBVAE1000037|Los nombres del responsable de pago tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC010011','BBVAE1000038|Los nombres del Contratante tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA010011','BBVAE1000039|Los nombres del Asegurado tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR010004','BBVAE1000040|Los nombres del Responsable de Pago supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC010004','BBVAE1000041|Los nombes del Contratante supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA010004','BBVAE1000042|El apellido Materno del Asegurado supera los 30 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR011001','BBVAE1000043|La fecha de nacimiento del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC011001','BBVAE1000044|La fecha de nacimiento del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA011001','BBVAE1000045|La fecha de nacimiento del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR011010','BBVAE1000046|El campo fechaNacimiento de persona responsable debe ser un correo con formato v'||chr(225)||'lido','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC011010','BBVAE1000047|El campo fechaNacimiento de persona contratante debe ser un correo con formato v'||chr(225)||'lido','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA011010','BBVAE1000048|El campo fechaNacimiento de persona asegurado debe ser un correo con formato v'||chr(225)||'lido','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR011002','BBVAE1000049|La fecha de nacimiento del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC011002','BBVAE1000050|La fecha de nacimiento del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA011002','BBVAE1000051|La fecha de nacimiento del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR012001','BBVAE1000052|El sexo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC012001','BBVAE1000053|El sexo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA012001','BBVAE1000054|El sexo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR012002','BBVAE1000055|El sexo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC012002','BBVAE1000056|El sexo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA012002','BBVAE1000057|El sexo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR012006','BBVAE1000058|El sexo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC012006','BBVAE1000059|El sexo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA012006','BBVAE1000060|El sexo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR013001','BBVAE1000061|La direcci'||chr(243)||'n de correo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC013001','BBVAE1000062|La direcci'||chr(243)||'n de correo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA013001','BBVAE1000063|La direcci'||chr(243)||'n de correo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR013011','BBVAE1000064|El celular del Responsable de Pago tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC013011','BBVAE1000065|El celular del Contratante tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA013011','BBVAE1000066|El celular del Asegurado tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR013010','BBVAE1000067|La direcci'||chr(243)||'n de correo del Responsable de Pago debe tener un correo formato v'||chr(225)||'lido. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC013010','BBVAE1000068|La direcci'||chr(243)||'n de correo del Contratante debe tener un correo formato v'||chr(225)||'lido. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA013010','BBVAE1000069|La direcci'||chr(243)||'n de correo del Asegurado debe tener un correo formato v'||chr(225)||'lido. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR013002','BBVAE1000070|La direcci'||chr(243)||'n de correo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC013002','BBVAE1000071|La direcci'||chr(243)||'n de correo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA013002','BBVAE1000072|La direcci'||chr(243)||'n de correo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR016001','BBVAE1000073|El celular del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC016001','BBVAE1000074|El celular del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA016001','BBVAE1000075|El celular del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR016002','BBVAE1000076|El celular del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC016002','BBVAE1000077|El celular del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA016002','BBVAE1000078|El celular del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR016011','BBVAE1000079|El formato del celular del responsable de pago deben ser solo n'||chr(250)||'mero entre 0-9. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC016011','BBVAE1000080|El formato del celular del contratante deben ser solo n'||chr(250)||'mero entre 0-9. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA016011','BBVAE1000081|El formato del celular del asegurado deben ser solo n'||chr(250)||'mero entre 0-9. Por favor actualizar la informaci'||chr(243)||'n en Nacar o PIC.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR016004','BBVAE1000082|El celular del Responsable de Pago supera los 12 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC016004','BBVAE1000083|El celular del Contratante supera los 12 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA016004','BBVAE1000084|El celular del Asegurado supera los 12 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PR016003','BBVAE1000085|El celular del Responsable de Pago debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PC016003','BBVAE1000086|El celular del Contratante debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','PA016003','BBVAE1000087|El celular del Asegurado debe tener al menos 9 caracteres. Verificar si el documento tienen ceros a la izquierda o numeros adicionales','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR011002','BBVAE1000088|El tipo de v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC011002','BBVAE1000089|El tipo de v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA011002','BBVAE1000090|El tipo de v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR011001','BBVAE1000091|El tipo de v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC011001','BBVAE1000092|El tipo de v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA011001','BBVAE1000093|El tipo de v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR011011','BBVAE1000094|El tipo de v'||chr(237)||'a del Responsable de Pago tiene caracteres extraños tales como ("%","#", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR011004','BBVAE1000095|El tipo de v'||chr(237)||'a del Responsable de Pago supera los 3 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC011011','BBVAE1000096|El tipo de v'||chr(237)||'a del Contratante tiene caracteres extraños tales como ("%","#", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC011004','BBVAE1000097|El tipo de v'||chr(237)||'a del Contratante supera los 3 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA011011','BBVAE1000098|El tipo de v'||chr(237)||'a del Asegurado tiene caracteres extraños tales como ("%","#", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA011004','BBVAE1000099|El tipo de v'||chr(237)||'a del Asegurado supera los 3 caracteres. De presentarse este caso, contactar a Network Support.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR009002','BBVAE1000100|El nombre de la v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC009002','BBVAE1000101|El nombre de la v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA009002','BBVAE1000102|El nombre de la v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR009001','BBVAE1000103|El nombre de la v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC009001','BBVAE1000104|El nombre de la v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA009001','BBVAE1000105|El nombre de la v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR009011','BBVAE1000106|El nombre de la v'||chr(237)||'a del Responsable de Pago tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC009011','BBVAE1000107|El nombre de la v'||chr(237)||'a del Contratante tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA009011','BBVAE1000108|El nombre de la v'||chr(237)||'a del Asegurado tiene caracteres extraños tales como ("$","+", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR010002','BBVAE1000109|El nombre de la v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC010002','BBVAE1000110|El nombre de la v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA010002','BBVAE1000111|El nombre de la v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR010001','BBVAE1000112|El nombre de la v'||chr(237)||'a del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC010001','BBVAE1000113|El nombre de la v'||chr(237)||'a del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA010001','BBVAE1000114|El nombre de la v'||chr(237)||'a del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR010011','BBVAE1000115|El n'||chr(250)||'mero de la v'||chr(237)||'a del Responsable de Pago tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC010011','BBVAE1000116|El n'||chr(250)||'mero de la v'||chr(237)||'a del Contratante tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA010011','BBVAE1000117|El n'||chr(250)||'mero de la v'||chr(237)||'a del Asegurado tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR013001','BBVAE1000118|El ubigeo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC013001','BBVAE1000119|El ubigeo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA013001','BBVAE1000120|El ubigeo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR013002','BBVAE1000121|El ubigeo del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC013002','BBVAE1000122|El ubigeo del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA013002','BBVAE1000123|El ubigeo del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR003001','BBVAE1000124|El distrito del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC003001','BBVAE1000125|El distrito del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA003001','BBVAE1000126|El distrito del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR005001','BBVAE1000127|El provincia del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC005001','BBVAE1000128|El provincia del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA005001','BBVAE1000129|El provincia del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR005002','BBVAE1000130|El provincia del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC005002','BBVAE1000131|El provincia del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA005002','BBVAE1000132|El provincia del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR001001','BBVAE1000133|La direcci'||chr(243)||'n del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC001001','BBVAE1000134|La direcci'||chr(243)||'n del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA001001','BBVAE1000135|La direcci'||chr(243)||'n del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR001002','BBVAE1000136|La direcci'||chr(243)||'n del Responsable de Pago debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC001002','BBVAE1000137|La direcci'||chr(243)||'n del Contratante debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA001002','BBVAE1000138|La direcci'||chr(243)||'n del Asegurado debe ser enviado como parte de los datos del alta  y no debe estar vac'||chr(237)||'o. Verificar y corregir en Nacar o PIC, si el error persiste contactar al Network Support','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UR001011','BBVAE1000139|La direcci'||chr(243)||'n del Responsable de Pago tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UC001011','BBVAE1000140|La direcci'||chr(243)||'n del Contratante tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC001','UA001011','BBVAE1000141|La direcci'||chr(243)||'n del Asegurado tiene caracteres extraños tales como ("$","%", "@"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;

INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','00000000','Errores funcionales para el canal PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;

INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000027','BBVAE2000001|El nombre del responsable de pago no corresponde al DNI ingresado. Verificar la informaci'||chr(243)||'n brindada por el cliente  y actualizar de ser necesario.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000022','BBVAE2000002|El apellido paterno del responsable de pago tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000023','BBVAE2000003|El apellido paterno del contratante  tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del cliente en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000021','BBVAE2000004|El apellido paterno del asegurado tiene caracteres extraños tales como ("@","/", "+"): Corregir la informaci'||chr(243)||'n del asegurado en Nacar o PIC','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000028','BBVAE2000005|El apellido  paterno CAROSIO del responsable de pago no corresponde al DNI 00020726. Verificar la informaci'||chr(243)||'n brindada por el cliente  y actualizar de ser necesario.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000029','BBVAE2000006|El apellido  materno  HERECLIA del responsable de pago no corresponde al DNI 00020726. Verificar la informaci'||chr(243)||'n brindada por el cliente  y actualizar de ser necesario.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000031','BBVAE2000007|La fecha de nacimiento 1959-06-28 del responsable de pago no corresponde al DNI 00020726. Verificar la informaci'||chr(243)||'n brindada por el cliente  y actualizar de ser necesario.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('PC002','CO000030','BBVAE2000008|El sexo M del Responsable de Pago no corresponde al Pasaporte 306901068. Verificar la informaci'||chr(243)||'n brindada por el cliente  y actualizar de ser necesario.','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;