INSERT INTO PISD.T_PISD_INSRNC_PRT_ROLE (PARTICIPANT_ROLE_ID, ROLE_NAME, PARTICIPANT_ROLE_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (7, 'RESPONSABLE DE PAGO', 'RESPONSABLE DE PAGO','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_COMPANY_ROLE set PARTICIPANT_ROLE_ID = 7 WHERE INSURANCE_COMPANY_ROLE_ID = '23' AND INSURANCE_COMPANY_ID = 1;
COMMIT;