INSERT INTO PISD.T_PISD_INSURANCE_CATALOG (KEY_CATALOG_ID,CATALOG_ELEMENT_ID,CATALOG_ELEMENT_DESC,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES ('830100','1','Indicador para habilitacion de numeros extranjeros en aplicativos','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);
COMMIT;