SET LINESIZE 2500;
SET PAGESIZE 5000;
SELECT
    C.INSURANCE_CONTRACT_ENTITY_ID,
    C.INSURANCE_CONTRACT_BRANCH_ID,
    C.CONTRACT_FIRST_VERFN_DIGIT_ID,
    C.CONTRACT_SECOND_VERFN_DIGIT_ID,
    C.INSRC_CONTRACT_INT_ACCOUNT_ID,
    C.POLICY_ID,
    C.CUSTOMER_ID,
    C.INSURANCE_PRODUCT_ID,
    C.PAYMENT_MEANS_TYPE,
    P.INSURANCE_PRODUCT_NAME,
    C.INSURANCE_MODALITY_TYPE,
    C.CONTRACT_STATUS_ID,
    C.OPENPAY_CUSTOMER_CARD_TOKENIZED_ID,
    R.POLICY_RECEIPT_ID,
    R.INSURANCE_COMPANY_RECEIPT_ID,
    R.PREMIUM_PAYMENT_RECEIPT_AMOUNT,
    R.CURRENCY_ID,
    R.RECEIPT_STATUS_TYPE,
    R.RECEIPT_START_DATE,
    R.RECEIPT_END_DATE
FROM PISD.T_PISD_INSURANCE_CONTRACT C
INNER JOIN PISD.T_PISD_INSURANCE_CTR_RECEIPTS R
    ON C.INSURANCE_CONTRACT_ENTITY_ID = R.INSURANCE_CONTRACT_ENTITY_ID
    AND C.INSURANCE_CONTRACT_BRANCH_ID = R.INSURANCE_CONTRACT_BRANCH_ID
    AND C.INSRC_CONTRACT_INT_ACCOUNT_ID = R.INSRC_CONTRACT_INT_ACCOUNT_ID
INNER JOIN PISD.t_pisd_insurance_product P
    ON C.INSURANCE_PRODUCT_ID = P.INSURANCE_PRODUCT_ID
WHERE
    C.PAYMENT_MEANS_TYPE = :PAYMENT_MEANS_TYPE
  AND C.CONTRACT_STATUS_ID = :CONTRACT_STATUS_ID
  AND R.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE
