
  UPDATE PISD.T_PISD_INSURANCE_PRODUCT
  SET  INSURANCE_RISK_BUSINESS_ID =10,
       INSURANCE_TYPE_ID= 1,
       INSURANCE_PRODUCT_DESC ='SEGURO VIDA DINAMICO',
       INSURANCE_PRODUCT_NAME ='SEG. VIDA DINAMICO' ,
       INSURANCE_PRODUCT_TYPE = '841',
       GIFT_PRODUCT_TYPE ='N',
       SIMLT_VALIDITY_DAYS_NUMBER= 30,
       COLLECTIVE_POLICY_TYPE= 'N',
       ATTEMPT_CLCT_INSRC_CNCL_TYPE ='R',
       CHARGE_ATTEMPTS_NUMBER = 90,
       JOINT_IND_TYPE = 'N',
       BILLING_RATE_CHANGE_IND_TYPE='N',
       DEFERRED_ENTRY_IND_TYPE='N',
       HEALTH_EVAL_MARK_TYPE= 'N',
       REGISTRY_SITUATION_TYPE='01',
       CREATION_USER_ID = 'BATCH',
       CREATION_DATE = SYSTIMESTAMP,
       USER_AUDIT_ID  = 'BATCH',
       AUDIT_DATE = SYSTIMESTAMP,
       PRODUCT_SHORT_DESC ='VIDADINAMICO'
  WHERE INSURANCE_PRODUCT_ID = 9;


  UPDATE PISD.T_PISD_INSURANCE_PRODUCT
  SET  INSURANCE_RISK_BUSINESS_ID =10,
       INSURANCE_TYPE_ID= 1,
       INSURANCE_PRODUCT_DESC ='Prueba batch',
       INSURANCE_PRODUCT_NAME ='Prueba batch' ,
       INSURANCE_PRODUCT_TYPE = '123',
       CREATION_USER_ID = 'BATCH',
       CREATION_DATE = SYSTIMESTAMP,
       USER_AUDIT_ID  = 'BATCH',
       AUDIT_DATE = SYSTIMESTAMP,
       PRODUCT_SHORT_DESC ='test batch'
  WHERE INSURANCE_PRODUCT_ID = 130;

  UPDATE PISD.T_PISD_INSURANCE_RATE SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURANCE_MOD_SCHAN SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_MODALITY_INSRNC_CNSD SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_SCHAN_INSRNC_MOD_FEE SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRC_MOD_SCHAN_OPER SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_MOD_PAY_PERIOD SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_QUOTATION_MOD SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_QUOTATION_VEH SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_ROLE_MODALITY SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_SIMLT_PRD SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_SIMLT_VEHICLE SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURANCE_CONTRACT SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_DETL_VCHR_PMT SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURANCE_VOUCHER_PMT SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURANCE_OFFER SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURED_QUOTATION_HSNG SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_SIMLT_INSURED_HOUSING SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSRNC_CONTRACT_HIST SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_QUOTA_INSRNC_ADDL_CRD SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;
  UPDATE PISD.T_PISD_INSURANCE_REQUEST_CNCL SET INSURANCE_PRODUCT_ID = 9 WHERE INSURANCE_PRODUCT_ID = 130;