--INSERTAR PRODUCTO POR MODALIDAD
-- VALIDAR LA FECHA START - INSRNC_MOD_VLDY_START_DATE: 01/12/22 *******
-- VALIDAR EL CODIGO DE PLAN FLEXIBLE EN RIMAC - INSURANCE_COMPANY_MODALITY_ID: 533740 ******
INSERT INTO PISD.T_PISD_INSRNC_PRD_MODALITY (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_COMPANY_ID,INSURANCE_COMPANY_MODALITY_ID,CURRENCY_ID,INSUR_MODALITY_DESC,INSURANCE_MODALITY_NAME,OPERATION_GLOSSARY_DESC,INSRNC_MOD_VLDY_START_DATE,INSRNC_MODALITY_VLDY_END_DATE,CUMULUS_MARK_TYPE,CUMULUS_CLAUSE_ID,INSURANCE_EXPIRATION_TYPE,CONTRACT_DURATION_TYPE,CONTRACT_DURATION_NUMBER,INSRNC_MODALITY_MIN_PDS_NUMBER,INSRNC_MODALITY_MAX_PDS_NUMBER,QUOTA_VALIDITY_DAYS_NUMBER,INSRNC_ANNUL_DAYS_MAX_NUMBER,SUGGESTED_MODALITY_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE, FLEXIBLE_COVRG_PLAN_IND_TYPE, NEW_MODALITY_IND_TYPE)
VALUES (1,'04',1,'440335','USD','PLAN 4 FLEXIBLE','PLAN FLEXIBLE','SEG.VE',TO_DATE('01/12/2022','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),'N',NULL,'A','A',1,1,1,30,90,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP,'S', 'S');

--INSERTAR PRODUCTO MODALIDAD CANAL
--  Añadir Plan AutoFlexible para PIC
-- Validar fecha start - CHANNEL_SALE_START_DATE: 01/11/2022 *************
INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE, PUBLICATION_ORDER_NUMBER)
VALUES (1,'04','PC',TO_DATE('01/11/2022','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP, 4);

--  Añadir Plan AutoFlexible para BxI
INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE, PUBLICATION_ORDER_NUMBER)
VALUES (1,'04','BI',TO_DATE('01/11/2022','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP, 4);

--  Añadir Plan AutoFlexible para Telemarketing
INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE, PUBLICATION_ORDER_NUMBER)
VALUES (1,'04','TM',TO_DATE('01/11/2022','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP, 4);


-- AGREGAR NUMERO DE CUENTA DE RIMAC
-- CONFIRMAR CUENTA DE RIMAC **********
UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_CONTRACT_ID = '00110586580100047842'
WHERE INSURANCE_PRODUCT_ID = 1  AND INSURANCE_MODALITY_TYPE='04';
COMMIT;



--INSERTAR COMISIONES
--CONFIRMAR COMISIONES **********

--COMISION PARA PIC
--validar FEE_START_DATE: 01/01/2023
--VALIDAR PORCENTAJE DE COMISION - POLICY_COMMISSION_PER: 21.00000
INSERT INTO PISD.T_PISD_SCHAN_INSRNC_MOD_FEE (FEE_ID, INSURANCE_PRODUCT_ID, INSURANCE_MODALITY_TYPE, SALE_CHANNEL_ID, FEE_SUBTYPE_TYPE, FEE_START_DATE, FEE_END_DATE, INSURED_MINIMUM_AGE_NUMBER, INSURED_MAXIMUM_AGE_NUMBER, GRACE_PD_INSRNC_FEE_IND_TYPE, POLICY_ISSUE_RIGHTS_PER, IGV_AFFECTED_TYPE, POLICY_COMMISSION_PER, REGISTRY_SITUATION_TYPE, CREATION_USER_ID, CREATION_DATE, USER_AUDIT_ID, AUDIT_DATE, CURRENCY_ID) 
VALUES(52, 1, '04', 'PC', '01', TO_DATE('01/01/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), 18, 75, 'N', 3.0, 'S', 21.00000, '01', 'BATCH', SYSDATE, 'BATCH', SYSDATE, 'USD');

--COMISION PARA TM
INSERT INTO PISD.T_PISD_SCHAN_INSRNC_MOD_FEE (FEE_ID, INSURANCE_PRODUCT_ID, INSURANCE_MODALITY_TYPE, SALE_CHANNEL_ID, FEE_SUBTYPE_TYPE, FEE_START_DATE, FEE_END_DATE, INSURED_MINIMUM_AGE_NUMBER, INSURED_MAXIMUM_AGE_NUMBER, GRACE_PD_INSRNC_FEE_IND_TYPE, POLICY_ISSUE_RIGHTS_PER, IGV_AFFECTED_TYPE, POLICY_COMMISSION_PER, REGISTRY_SITUATION_TYPE, CREATION_USER_ID, CREATION_DATE, USER_AUDIT_ID, AUDIT_DATE, CURRENCY_ID)
VALUES(53, 1, '04', 'TM', '01', TO_DATE('01/01/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), 18, 75, 'N', 3.0, 'S', 12.25, '01', 'BATCH', SYSDATE, 'BATCH', SYSDATE, 'USD');

--COMISION PARA BI
INSERT INTO PISD.T_PISD_SCHAN_INSRNC_MOD_FEE (FEE_ID, INSURANCE_PRODUCT_ID, INSURANCE_MODALITY_TYPE, SALE_CHANNEL_ID, FEE_SUBTYPE_TYPE, FEE_START_DATE, FEE_END_DATE, INSURED_MINIMUM_AGE_NUMBER, INSURED_MAXIMUM_AGE_NUMBER, GRACE_PD_INSRNC_FEE_IND_TYPE, POLICY_ISSUE_RIGHTS_PER, IGV_AFFECTED_TYPE, POLICY_COMMISSION_PER, REGISTRY_SITUATION_TYPE, CREATION_USER_ID, CREATION_DATE, USER_AUDIT_ID, AUDIT_DATE, CURRENCY_ID)
VALUES(54, 1, '04', 'BI', '01', TO_DATE('01/01/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), 18, 75, 'N', 3.0, 'S', 21.00000, '01', 'BATCH', SYSDATE, 'BATCH', SYSDATE, 'USD');


--INSERTAR CONSIDERACIONES

--INSERTAR DEDUCIBLES
INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
80,'DE','T','Si utilizas la cobertura de Vehiculo de reemplazo pagaras US$ 100.00.',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
81,'DE','T','Robo de Accesorios musicales pagaras el 10% del monto a indemnizar (monto minimo US$150). ',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);


--INSERTAR EXCLUSIONES
INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
82,'EX','T','Podras encontrar el  listado completo de las exclusiones en nuestra pagina web, en la seccion de Seguros.',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
83,'EX','T','No llevar puesto el cinturon de seguridad',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);


--INSERTAR VEHICULOS NO ASEGURABLES
INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
84,'VN','T','Vehiculos de timon cambiado',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
85,'VN','T','Vehiculos menores (motocicletas, mototaxis y similares)',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

--INSERTAR BENEFICIOS
INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
86,'BE','T','Vehiculo de reemplazo (con costo).',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_INSRNC_CONSIDERATION (
INSURANCE_CONSIDERATION_ID,INSURANCE_CONSIDERATION_TYPE,
INSRC_CNSD_DATA_VALUE_TYPE,INSURANCE_CONSIDERATION_DESC,
INSURANCE_CONSIDERATION_AMOUNT,CURRENCY_ID,INSURANCE_CONSIDERATION_PER,
REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE) VALUES (
87,'BE','T','Descuentos en Repsol y Baterias Etna Express.',0,'',0,'01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);


--INSERTAR CONSIDERACIONES POR MODALIDAD Y PRODUCTO
INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',80,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),60,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',81,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),61,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',82,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),62,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',83,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),63,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',84,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),64,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',85,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),65,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',86,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),66,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_MODALITY_INSRNC_CNSD (
INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,INSURANCE_CONSIDERATION_ID,CONSIDERATION_START_DATE,CONSIDERATION_END_DATE,CNSD_PUBLICATION_ORDER_NUMBER,
MAIN_CONSIDERATION_IND_TYPE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE)
VALUES (1,'04',87,TO_DATE('01/08/2021','DD/MM/YYYY'),TO_DATE('31/12/9999','DD/MM/YYYY'),67,'N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);