SET LINESIZE 2500;
SET PAGESIZE 5000;
SET sqlblanklines on;
SET trimspool ON;
COLUMN * FORMAT A500;

SELECT * FROM PBTQ.T_PBTQ_CUSTOMER_RESERVED_INFO     WHERE rownum <= 40;
SELECT * FROM PBTQ.T_PBTQ_EMAIL_VAL_PROC_STT_QRY     WHERE rownum <= 40;
SELECT * FROM PBTQ.T_PBTQ_INDICATORS_CATALOG         WHERE rownum <= 40;
SELECT * FROM PBTQ.T_PBTQ_NO_CUST_ATTEMPT_CTRNG      WHERE rownum <= 40;
SELECT * FROM PBTQ.T_PBTQ_CUSTOMERS_INDICATORS       WHERE rownum <= 40;
SELECT * FROM PBTQ.T_PBTQ_NO_CUSTOMER_DETL           WHERE rownum <= 40;