SET LINESIZE 3500;
SET PAGESIZE 9050;

COLUMN CERTIFICADO_BANCO               HEADING 'CERTIFICADO_BANCO'  FORMAT A23;
COLUMN PLACA_VEHICULO                  HEADING 'PLACA_VEHICULO' FORMAT A40;
COLUMN MOTOR_DEL_VEHICULO              HEADING 'MOTOR_DEL_VEHICULO' FORMAT A30;
COLUMN NUMERO_DE_SERIE                 HEADING 'NUMERO_DE_SERIE' FORMAT A25;

SELECT CT.INSURANCE_CONTRACT_ENTITY_ID||CT.INSURANCE_CONTRACT_BRANCH_ID||
       CT.CONTRACT_FIRST_VERFN_DIGIT_ID||CT.CONTRACT_SECOND_VERFN_DIGIT_ID||
       CT.INSRC_CONTRACT_INT_ACCOUNT_ID CERTIFICADO_BANCO,
       SV.VEHICLE_LICENSE_ID PLACA_VEHICULO,
       QV.VEHICLE_ENGINE_ID MOTOR_DEL_VEHICULO,
       QV.CHASSIS_ID NUMERO_DE_SERIE,
       CT.CTRCT_DISPUTE_STATUS_TYPE,
       CT.CREATION_DATE
FROM PISD.T_PISD_INSURANCE_CONTRACT CT
         INNER JOIN PISD.T_PISD_INSRNC_QUOTATION_VEH QV ON CT.POLICY_QUOTA_INTERNAL_ID = QV.POLICY_QUOTA_INTERNAL_ID
    AND CT.INSURANCE_PRODUCT_ID = QV.INSURANCE_PRODUCT_ID
    AND CT.INSURANCE_MODALITY_TYPE = QV.INSURANCE_MODALITY_TYPE
         INNER JOIN PISD.T_PISD_INSURANCE_QUOTATION IQ ON CT.POLICY_QUOTA_INTERNAL_ID = IQ.POLICY_QUOTA_INTERNAL_ID
         INNER JOIN PISD.T_PISD_INSRNC_SIMLT_VEHICLE SV ON IQ.INSURANCE_SIMULATION_ID = SV.INSURANCE_SIMULATION_ID
WHERE CT.INSURANCE_PRODUCT_ID = '1'
ORDER BY CT.CREATION_DATE DESC;