SET LINESIZE 2500;
SET PAGESIZE 5000;

SELECT GF_PROCESS_NUMBER_ID,G_NON_CUSTOMER_ID,GF_PROCESS_NUMBER_ID FROM KONB.T_KONB_CUSTOMER WHERE rownum <= 30;
SELECT GF_COMPANY_ID,GF_PROCESS_NUMBER_ID FROM KONB.T_KONB_CUSTOMER WHERE rownum <= 30;