SET LINESIZE 2500;
SET PAGESIZE 5000;
SET sqlblanklines on;
SET trimspool ON;
COLUMN * FORMAT A500;

SELECT * FROM PBFD.T_PBFD_BMTR_PROCESS_RULES     WHERE rownum <= 40 ORDER BY CREATION_DATE DESC;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_BMTR_PROCESS_RULES
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_FAIL_ATMPT_BMTR_PROC
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_BIOMETRIC_PROCESS_LOGS
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_ATTACHS_BMTRC_PROCESS
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_SCORES_BMTR_PROCESS
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;

SELECT *
FROM (
         SELECT *
         FROM PBFD.T_PBFD_CONTROLS_BMTR_PROCESS
         WHERE EXTRACT(YEAR FROM CREATION_DATE) = EXTRACT(YEAR FROM SYSDATE) -- Filtrar por el año actual
         ORDER BY CREATION_DATE DESC
     )
WHERE ROWNUM <= 40;
