SET LINESIZE 2500;
SET PAGESIZE 9000;


COLUMN POLICY_QUOTA_INTERNAL_ID             HEADING 'POLICY_QUOTA_INTERNAL_ID' FORMAT A20;
COLUMN INSURANCE_PRODUCT_ID                 HEADING 'PRODUCT_ID' FORMAT 9999;
COLUMN INSURANCE_MODALITY_TYPE              HEADING 'MODALITY' FORMAT A8;
COLUMN INSURED_AMOUNT                       HEADING 'INSURED_AMOUNT' FORMAT 9999999999999.99;
COLUMN CURRENCY_ID                          HEADING 'CURRENCY' FORMAT A8;
COLUMN PERIOD_TYPE                          HEADING 'PERIOD_tYPE' FORMAT A10;
COLUMN PERIOD_NUMBER                        HEADING 'PERIOD_NUMBER' FORMAT 999999;
COLUMN TOTAL_RETURN_AMOUNT                  HEADING 'TOTAL_RETURN' FORMAT 999999999999.99;
COLUMN INSURED_ID                           HEADING 'INSURED_ID' FORMAT A20;
COLUMN CUSTOMER_DOCUMENT_TYPE               HEADING 'DOCUMENT' FORMAT A10;
COLUMN PERSONAL_ID                          HEADING 'PERSONAL_ID' FORMAT A20;
COLUMN IS_BBVA_CUSTOMER_TYPE                HEADING 'IS_CUSTOMER' FORMAT A10;
COLUMN CUSTOMER_ENTRY_DATE                  HEADING 'ENTRY_DATE' FORMAT A20;
COLUMN PARTICIPANT_ROLE_ID                  HEADING 'ROLE' FORMAT 9999;
COLUMN INSURED_CUSTOMER_NAME                HEADING 'INSURED_CUSTOMER_NAME' FORMAT A40;
COLUMN CLIENT_LAST_NAME                     HEADING 'CLIENT_LAST_NAME' FORMAT A60;
COLUMN USER_EMAIL_PERSONAL_DESC             HEADING 'EMAIL' FORMAT A80;
COLUMN PHONE_ID                             HEADING 'PHONE_ID' FORMAT A15;
COLUMN CUSTOMER_BIRTH_DATE                  HEADING 'BIRTH_DATE' FORMAT A20;
COLUMN CREATION_USER_ID                     HEADING 'CREATION_USER' FORMAT A20;
COLUMN CREATION_DATE                        HEADING 'CREATION_DATE' FORMAT A30;
COLUMN USER_AUDIT_ID                        HEADING 'USER_AUDIT' FORMAT A20;
COLUMN AUDIT_DATE                           HEADING 'AUDIT_DATE' FORMAT A30;
COLUMN GENDER_ID                            HEADING 'GENDER' FORMAT A8;


SELECT
POLICY_QUOTA_INTERNAL_ID,
INSURANCE_PRODUCT_ID,
INSURANCE_MODALITY_TYPE,
INSURED_AMOUNT,
CURRENCY_ID,
PERIOD_TYPE,
PERIOD_NUMBER,
REFUND_PER,
TOTAL_RETURN_AMOUNT,
INSURED_ID,
CUSTOMER_DOCUMENT_TYPE,
PERSONAL_ID,
IS_BBVA_CUSTOMER_TYPE,
CUSTOMER_ENTRY_DATE,
PARTICIPANT_ROLE_ID,
INSURED_CUSTOMER_NAME,
CLIENT_LAST_NAME,
USER_EMAIL_PERSONAL_DESC,
PHONE_ID,
CUSTOMER_BIRTH_DATE,
CREATION_USER_ID,
CREATION_DATE,
USER_AUDIT_ID,
AUDIT_DATE,
GENDER_ID
FROM PISD.T_PISD_INSURED_QUOTATION_LIFE
order by CREATION_DATE desc;