UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
        AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
        AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689102';
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
  AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
  AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689103';
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
  AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
  AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689104';
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
  AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
  AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689105';
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
  AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
  AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689107';
COMMIT;
UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET
    PAYMENT_MEANS_TYPE = 'EXT'
WHERE
        INSURANCE_CONTRACT_ENTITY_ID = '0011'
  AND INSURANCE_CONTRACT_BRANCH_ID = '0123'
  AND INSRC_CONTRACT_INT_ACCOUNT_ID= '4813689108';
COMMIT;