INSERT INTO PISD.T_PISD_INSRNC_SALES_CHANNEL VALUES ('NC','NACAR','NACAR','N','01','BATCH',SYSTIMESTAMP,'BATCH',SYSTIMESTAMP);

INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE,PUBLICATION_ORDER_NUMBER)
VALUES (8,'01','NC',TO_DATE('04/07/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), '01','BATCH', SYSTIMESTAMP, 'BATCH', SYSTIMESTAMP,1);
INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE,PUBLICATION_ORDER_NUMBER)
VALUES (8,'02','NC',TO_DATE('04/07/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), '01','BATCH', SYSTIMESTAMP, 'BATCH', SYSTIMESTAMP,2);
INSERT INTO PISD.T_PISD_INSURANCE_MOD_SCHAN (INSURANCE_PRODUCT_ID,INSURANCE_MODALITY_TYPE,SALE_CHANNEL_ID,CHANNEL_SALE_START_DATE,CHANNEL_SALE_END_DATE,REGISTRY_SITUATION_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE,PUBLICATION_ORDER_NUMBER)
VALUES (8,'03','NC',TO_DATE('04/07/2023', 'dd/mm/yyyy'), TO_DATE('31/12/9999', 'dd/mm/yyyy'), '01','BATCH', SYSTIMESTAMP, 'BATCH', SYSTIMESTAMP,3);