UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_MODALITY_ID = '534254'
WHERE INSURANCE_PRODUCT_ID = 13
AND INSURANCE_MODALITY_TYPE = '01';

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_MODALITY_ID = '534273'
WHERE INSURANCE_PRODUCT_ID = 13
AND INSURANCE_MODALITY_TYPE = '03';

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_MODALITY_ID = '534272'
WHERE INSURANCE_PRODUCT_ID = 13
AND INSURANCE_MODALITY_TYPE = '02';


