UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET CONTRACT_STATUS_ID = 'PEB',
POLICY_ANNULATION_DATE = TO_DATE('28/12/23', 'DD/MM/YY')
WHERE (C.INSURANCE_CONTRACT_ENTITY_Id || C.INSURANCE_CONTRACT_BRANCH_ID || C.CONTRACT_FIRST_VERFN_DIGIT_ID ||
C.CONTRACT_SECOND_VERFN_DIGIT_ID || C.INSRC_CONTRACT_INT_ACCOUNT_ID) IN ('00110172434000036406');