UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET CONTRACT_STATUS_ID = 'PEB',
POLICY_ANNULATION_DATE = TO_DATE('28/12/23', 'DD/MM/YY')
WHERE (INSURANCE_CONTRACT_ENTITY_Id || INSURANCE_CONTRACT_BRANCH_ID || CONTRACT_FIRST_VERFN_DIGIT_ID ||
CONTRACT_SECOND_VERFN_DIGIT_ID || INSRC_CONTRACT_INT_ACCOUNT_ID) IN ('00110172434000036406');