UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET PRODUCT_SHORT_DESC = 'VEHICULAR' WHERE INSURANCE_PRODUCT_ID = 1;
UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET PRODUCT_SHORT_DESC = 'HOGAR_TOTAL' WHERE INSURANCE_PRODUCT_ID = 2;
UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET PRODUCT_SHORT_DESC = 'FLEXI_PYME' WHERE INSURANCE_PRODUCT_ID = 3;
UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET PRODUCT_SHORT_DESC = 'PROTECCION_TARJETA' WHERE INSURANCE_PRODUCT_ID = 4;
UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET PRODUCT_SHORT_DESC = 'EASYYES' WHERE INSURANCE_PRODUCT_ID = 8;