UPDATE PISD.T_PISD_INSURANCE_CATALOG
SET CATALOG_ELEMENT_DESC = 'CAJA RURAL DE AHORRO Y CREDITO CENCOSUD SCOTIA PERU S.A.|20543166660'
WHERE KEY_CATALOG_ID = '841006'
AND CATALOG_ELEMENT_ID = '21';

UPDATE PISD.T_PISD_INSURANCE_CATALOG
SET CATALOG_ELEMENT_DESC = 'CAJA RURAL DE AHORRO Y CREDITO RAIZ S.A.A|20231269071'
WHERE KEY_CATALOG_ID = '841006'
AND CATALOG_ELEMENT_ID = '26';

UPDATE PISD.T_PISD_INSURANCE_CATALOG
SET CATALOG_ELEMENT_DESC = 'BBVA CONSUMER FINANCE ENTIDAD DE DESARROLLO A LA PEQUENA Y MICRO EMPRESA-EDPYME|20553849161'
WHERE KEY_CATALOG_ID = '841006'
AND CATALOG_ELEMENT_ID = '29';

UPDATE PISD.T_PISD_INSURANCE_CATALOG
SET CATALOG_ELEMENT_DESC = 'BBBVA CONSUMER FINANCE ENTIDAD DE DESARROLLO A LA PEQUENA Y MICRO EMPRESA-EDPYME|120553849161'
WHERE KEY_CATALOG_ID = '841006'
AND CATALOG_ELEMENT_ID = '31';


UPDATE PISD.T_PISD_INSURANCE_CATALOG
SET CATALOG_ELEMENT_DESC = 'CAJA RURAL DE AHORRO Y CREDITO DEL CENTRO SA - CRAC DEL CENTRO SA|20568444737'
WHERE KEY_CATALOG_ID = '841006'
AND CATALOG_ELEMENT_ID = '35';


