UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET POLICY_ANNULATION_DATE = TO_DATE('21-JAN-24', 'DD/MM/YY')
WHERE INSURANCE_CONTRACT_ENTITY_ID = '0011'
AND INSURANCE_CONTRACT_BRANCH_ID = '0172'
AND CONTRACT_FIRST_VERFN_DIGIT_ID = '4'
AND CONTRACT_SECOND_VERFN_DIGIT_ID = '1'
AND INSRC_CONTRACT_INT_ACCOUNT_ID = '4000041183';

UPDATE PISD.T_PISD_INSURANCE_CONTRACT
SET POLICY_ANNULATION_DATE = TO_DATE('19-JAN-24', 'DD/MM/YY')
WHERE INSURANCE_CONTRACT_ENTITY_ID = '0011'
AND INSURANCE_CONTRACT_BRANCH_ID = '0172'
AND CONTRACT_FIRST_VERFN_DIGIT_ID = '4'
AND CONTRACT_SECOND_VERFN_DIGIT_ID = '4'
AND INSRC_CONTRACT_INT_ACCOUNT_ID = '4000041167';

