UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSURANCE_COMPANY_MODALITY_ID='440335', INSURANCE_COMPANY_CONTRACT_ID='00110586580100047842' WHERE INSURANCE_PRODUCT_ID = 1 AND INSURANCE_MODALITY_TYPE = '04'; 
COMMIT;

UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET INSURANCE_PRODUCT_DESC = 'SEGURO RESPALDO TOTAL', INSURANCE_PRODUCT_NAME = 'SEG. RESPALDO TOTAL' WHERE INSURANCE_PRODUCT_ID = 9;
COMMIT;

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSUR_MODALITY_DESC = 'PLAN SIN DEVOLUCION', INSURANCE_MODALITY_NAME = 'SEGURO DE RESPALDO TOTAL SIN DEVOLUCION' WHERE INSURANCE_PRODUCT_ID = 9 AND INSURANCE_MODALITY_TYPE = '01';
COMMIT;

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY SET INSUR_MODALITY_DESC = 'PLAN CON DEVOLUCION', INSURANCE_MODALITY_NAME = 'SEGURO DE RESPALDO TOTAL CON DEVOLUCION' WHERE INSURANCE_PRODUCT_ID = 9 AND INSURANCE_MODALITY_TYPE = '02';
COMMIT;