UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_MODALITY_ID = '533726'
WHERE INSURANCE_PRODUCT_ID = 130
AND INSURANCE_MODALITY_TYPE = '01';

UPDATE PISD.T_PISD_INSRNC_PRD_MODALITY
SET INSURANCE_COMPANY_MODALITY_ID = '533741'
WHERE INSURANCE_PRODUCT_ID = 130
AND INSURANCE_MODALITY_TYPE = '02';
