UPDATE PISD.T_PISD_INSURANCE_PRODUCT SET CT_RENEW_SEND_ADV_DAYS_NUMBER = '50' WHERE INSURANCE_PRODUCT_TYPE = '834';

update PISD.T_PISD_INSURANCE_CATALOG set CATALOG_ELEMENT_DESC='10' where KEY_CATALOG_ID='830014' and CATALOG_ELEMENT_ID='001';

commit;