UPDATE PISD.T_PISD_SCHAN_INSRNC_MOD_FEE
SET POLICY_COMMISSION_PER = 25
WHERE INSURANCE_PRODUCT_ID = 2
AND SALE_CHANNEL_ID IN ('PC', 'BI');

UPDATE PISD.T_PISD_SCHAN_INSRNC_MOD_FEE
SET POLICY_COMMISSION_PER = 55
WHERE INSURANCE_PRODUCT_ID = 4
AND SALE_CHANNEL_ID IN ('PC', 'BI');
