SELECT A.INSURANCE_CONTRACT_ENTITY_ID, 
       A.INSURANCE_CONTRACT_BRANCH_ID, 
       A.INSRC_CONTRACT_INT_ACCOUNT_ID, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       A.CURRENCY_ID, 
       to_char(A.RECEIPT_EXPIRATION_DATE, 'YYYY-MM-DD') RECEIPT_EXPIRATION_DATE, 
       to_char(A.RECEIPT_START_DATE, 'YYYY-MM-DD') RECEIPT_START_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE, 
       B.INSURANCE_PRODUCT_ID, 
       B.INSURANCE_MODALITY_TYPE, 
       B.INSURANCE_COMPANY_ID, 
       B.INSURANCE_CONTRACT_ENTITY_ID||B.INSURANCE_CONTRACT_BRANCH_ID||B.CONTRACT_FIRST_VERFN_DIGIT_ID||B.CONTRACT_SECOND_VERFN_DIGIT_ID||B.INSRC_CONTRACT_INT_ACCOUNT_ID as BANK_CERTIFICATE, 
       B.POLICY_ID, 
       A.POLICY_RECEIPT_ID, 
       C.INSUR_MODALITY_DESC, 
       A.MANAGEMENT_BRANCH_ID, 
       A.INSURANCE_COMPANY_RECEIPT_ID, 
       C.INSURANCE_COMPANY_CONTRACT_ID, 
       D.INSURANCE_PRODUCT_TYPE, 
       B.INSURANCE_COMPANY_PRODUCT_ID, 
       A.INSRNC_CO_RECEIPT_STATUS_TYPE, 
       A.RECEIPT_STATUS_TYPE, 
       TO_DATE(:RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE_VALUE, 
       B.CTRCT_DISPUTE_STATUS_TYPE, 
       B.PREMIUM_AMOUNT, 
       B.TOTAL_DEBT_AMOUNT, 
       B.PREV_PEND_BILL_RCPTS_NUMBER, 
       B.SETTLEMENT_FIX_PREMIUM_AMOUNT, 
       B.SETTLE_PENDING_PREMIUM_AMOUNT, 
       B.PREMIUM_AMOUNT, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       to_char(A.RECEIPT_CANCELLATION_DATE, 'YYYY-MM-DD') RECEIPT_CANCELLATION_DATE, 
       NVL(A.RENEWAL_RECEIPT_SEQ_NUMBER,A.POLICY_RECEIPT_ID) RENEWAL_RECEIPT_SEQ_NUMBER, NVL(A.RENEWAL_NUMBER,0) RENEWAL_NUMBER 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
         INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
    AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
    AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
         INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
         INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_COLLECTION_DATE <= TO_DATE(:RECEIPT_COLLECTION_DATE||' 23:59:59', 'YYYY-MM-DD HH24:MI:SS') 
  AND A.RECEIPT_COLLECTION_DATE > TO_DATE(:DATE_DAFAULT, 'YYYY-MM-DD') 
  AND A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
  AND A.PREMIUM_PAYMENT_RECEIPT_AMOUNT > :PREMIUM_PAYMENT_RECEIPT_AMOUNT 
  AND NVL(A.INSRNC_CO_RECEIPT_STATUS_TYPE, ' ') != :INSRNC_CO_RECEIPT_STATUS_TYPE 
AND D.INSURANCE_PRODUCT_TYPE NOT IN (:EXCLUDED_PRODUCTS) 
ORDER BY A.INSURANCE_CONTRACT_ENTITY_ID, A.INSURANCE_CONTRACT_BRANCH_ID, A.INSRC_CONTRACT_INT_ACCOUNT_ID, A.POLICY_RECEIPT_ID;


SELECT COUNT(*) COUNT 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
                                            AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
                                            AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_COLLECTION_DATE <= TO_DATE(:RECEIPT_COLLECTION_DATE||' 23:59:59', 'YYYY-MM-DD HH24:MI:SS') 
AND A.RECEIPT_COLLECTION_DATE > TO_DATE(:DATE_DAFAULT, 'YYYY-MM-DD') 
AND A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
AND A.PREMIUM_PAYMENT_RECEIPT_AMOUNT > :PREMIUM_PAYMENT_RECEIPT_AMOUNT 
AND NVL(A.INSRNC_CO_RECEIPT_STATUS_TYPE, ' ') != :INSRNC_CO_RECEIPT_STATUS_TYPE 
AND D.INSURANCE_PRODUCT_TYPE NOT IN (:EXCLUDED_PRODUCTS);


SELECT A.INSURANCE_CONTRACT_ENTITY_ID, 
       A.INSURANCE_CONTRACT_BRANCH_ID, 
       A.INSRC_CONTRACT_INT_ACCOUNT_ID, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       A.CURRENCY_ID, 
       to_char(A.RECEIPT_EXPIRATION_DATE, 'YYYY-MM-DD') RECEIPT_EXPIRATION_DATE, 
       to_char(A.RECEIPT_START_DATE, 'YYYY-MM-DD') RECEIPT_START_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE, 
       B.INSURANCE_PRODUCT_ID, 
       B.INSURANCE_MODALITY_TYPE, 
       B.INSURANCE_COMPANY_ID, 
       B.INSURANCE_CONTRACT_ENTITY_ID||B.INSURANCE_CONTRACT_BRANCH_ID||B.CONTRACT_FIRST_VERFN_DIGIT_ID||B.CONTRACT_SECOND_VERFN_DIGIT_ID||B.INSRC_CONTRACT_INT_ACCOUNT_ID as BANK_CERTIFICATE, 
       B.POLICY_ID, 
       A.POLICY_RECEIPT_ID, 
       C.INSUR_MODALITY_DESC, 
       A.MANAGEMENT_BRANCH_ID, 
       A.INSURANCE_COMPANY_RECEIPT_ID, 
       C.INSURANCE_COMPANY_CONTRACT_ID, 
       D.INSURANCE_PRODUCT_TYPE, 
       B.INSURANCE_COMPANY_PRODUCT_ID, 
       A.INSRNC_CO_RECEIPT_STATUS_TYPE, 
       A.RECEIPT_STATUS_TYPE, 
       TO_DATE(:RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE_VALUE, 
       B.CTRCT_DISPUTE_STATUS_TYPE, 
       B.PREMIUM_AMOUNT, 
       B.TOTAL_DEBT_AMOUNT, 
       B.PREV_PEND_BILL_RCPTS_NUMBER, 
       B.SETTLEMENT_FIX_PREMIUM_AMOUNT, 
       B.SETTLE_PENDING_PREMIUM_AMOUNT, 
       B.PREMIUM_AMOUNT, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       to_char(A.RECEIPT_CANCELLATION_DATE, 'YYYY-MM-DD') RECEIPT_CANCELLATION_DATE, 
       NVL(A.RENEWAL_RECEIPT_SEQ_NUMBER,A.POLICY_RECEIPT_ID) RENEWAL_RECEIPT_SEQ_NUMBER, NVL(A.RENEWAL_NUMBER,0) RENEWAL_NUMBER 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
         INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
    AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
    AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
         INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
         INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
  AND A.PAYMENT_METHOD_TYPE = :PAYMENT_METHOD_TYPE 
ORDER BY A.INSURANCE_CONTRACT_ENTITY_ID, A.INSURANCE_CONTRACT_BRANCH_ID, A.INSRC_CONTRACT_INT_ACCOUNT_ID, A.POLICY_RECEIPT_ID;


SELECT COUNT(*) COUNT 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
                                            AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
                                            AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
AND A.PAYMENT_METHOD_TYPE = :PAYMENT_METHOD_TYPE;


SELECT A.INSURANCE_CONTRACT_ENTITY_ID, 
       A.INSURANCE_CONTRACT_BRANCH_ID, 
       A.INSRC_CONTRACT_INT_ACCOUNT_ID, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       A.CURRENCY_ID, 
       to_char(A.RECEIPT_EXPIRATION_DATE, 'YYYY-MM-DD') RECEIPT_EXPIRATION_DATE, 
       to_char(A.RECEIPT_START_DATE, 'YYYY-MM-DD') RECEIPT_START_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_END_DATE, 'YYYY-MM-DD') RECEIPT_END_DATE, 
       to_char(A.RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE, 
       B.INSURANCE_PRODUCT_ID, 
       B.INSURANCE_MODALITY_TYPE, 
       B.INSURANCE_COMPANY_ID, 
       B.INSURANCE_CONTRACT_ENTITY_ID||B.INSURANCE_CONTRACT_BRANCH_ID||B.CONTRACT_FIRST_VERFN_DIGIT_ID||B.CONTRACT_SECOND_VERFN_DIGIT_ID||B.INSRC_CONTRACT_INT_ACCOUNT_ID as BANK_CERTIFICATE, 
       B.POLICY_ID, 
       A.POLICY_RECEIPT_ID, 
       C.INSUR_MODALITY_DESC, 
       A.MANAGEMENT_BRANCH_ID, 
       A.INSURANCE_COMPANY_RECEIPT_ID, 
       C.INSURANCE_COMPANY_CONTRACT_ID, 
       D.INSURANCE_PRODUCT_TYPE, 
       B.INSURANCE_COMPANY_PRODUCT_ID, 
       A.INSRNC_CO_RECEIPT_STATUS_TYPE, 
       A.RECEIPT_STATUS_TYPE, 
       TO_DATE(:RECEIPT_COLLECTION_DATE, 'YYYY-MM-DD') RECEIPT_COLLECTION_DATE_VALUE, 
       B.CTRCT_DISPUTE_STATUS_TYPE, 
       B.PREMIUM_AMOUNT, 
       B.TOTAL_DEBT_AMOUNT, 
       B.PREV_PEND_BILL_RCPTS_NUMBER, 
       B.SETTLEMENT_FIX_PREMIUM_AMOUNT, 
       B.SETTLE_PENDING_PREMIUM_AMOUNT, 
       B.PREMIUM_AMOUNT, 
       A.PREMIUM_PAYMENT_RECEIPT_AMOUNT, 
       to_char(A.RECEIPT_CANCELLATION_DATE, 'YYYY-MM-DD') RECEIPT_CANCELLATION_DATE, 
       NVL(A.RENEWAL_RECEIPT_SEQ_NUMBER,A.POLICY_RECEIPT_ID) RENEWAL_RECEIPT_SEQ_NUMBER, NVL(A.RENEWAL_NUMBER,0) RENEWAL_NUMBER 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
         INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
    AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
    AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
         INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
         INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
  AND TO_CHAR(A.OPENPAY_COMMERCE_TRANS_DATE,'YYYY-MM-DD') = TO_CHAR(:OPENPAY_COMMERCE_TRANS_DATE, 'YYYY-MM-DD') 
ORDER BY A.INSURANCE_CONTRACT_ENTITY_ID, A.INSURANCE_CONTRACT_BRANCH_ID, A.INSRC_CONTRACT_INT_ACCOUNT_ID, A.POLICY_RECEIPT_ID;


SELECT COUNT(*) COUNT 
FROM PISD.T_PISD_INSURANCE_CTR_RECEIPTS A 
INNER JOIN PISD.T_PISD_INSURANCE_CONTRACT B ON A.INSURANCE_CONTRACT_ENTITY_ID = B.INSURANCE_CONTRACT_ENTITY_ID 
                                            AND A.INSURANCE_CONTRACT_BRANCH_ID = B.INSURANCE_CONTRACT_BRANCH_ID 
                                            AND A.INSRC_CONTRACT_INT_ACCOUNT_ID = B.INSRC_CONTRACT_INT_ACCOUNT_ID 
INNER JOIN PISD.T_PISD_INSRNC_PRD_MODALITY C ON  C.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID AND C.INSURANCE_MODALITY_TYPE=B.INSURANCE_MODALITY_TYPE 
INNER JOIN PISD.T_PISD_INSURANCE_PRODUCT D ON D.INSURANCE_PRODUCT_ID = B.INSURANCE_PRODUCT_ID 
WHERE A.RECEIPT_STATUS_TYPE = :RECEIPT_STATUS_TYPE 
AND TO_CHAR(A.OPENPAY_COMMERCE_TRANS_DATE,'YYYY-MM-DD') = TO_CHAR(:OPENPAY_COMMERCE_TRANS_DATE, 'YYYY-MM-DD');